name: Docker Image CI

on:
  push:
    branches: [ "omxdevelop" ]
  pull_request:
    branches: [ "omxdevelop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image Jenkins_2.176.1_Debian_No_Java
      run: docker build . --file Dockerfile_Jenkins_2.176.1_Debian_No_Java --tag tomornb/jenkins:2.176.1_No_Java_$(date +%s)

    - name: Build the Docker image Jenkins_2.204.1_Debian_No_Java
      run: docker build . --file Dockerfile_Jenkins_2.204.1_Debian_No_Java --tag tomornb/jenkins:2.204.1_No_Java_$(date +%s)

    - name: Build the Docker image Jenkins_2.176.1_Debian_Java
      run: docker build . --file Dockerfile_Jenkins_2.176.1_Debian_Java --tag tomornb/jenkins:2.176.1_$(date +%s)
      
    - name: Build the Docker image Jenkins_2.204.1_Debian_Java
      run: docker build . --file Dockerfile_Jenkins_2.204.1_Debian_Java --tag tomornb/jenkins:2.204.1_$(date +%s)      
      